### ISSUE TITLE
dependant repos need to be added to deps.edn file

### ISSUE THREAD

**Issue by boxxxie** [suvash/one-time#14]
i have to add this to my deps.edn or clojure throws nonsense errors

```clojure
 :mvn/repos {
             "jitpack" {:url "https://jitpack.io"}
             "sonatype" {:url "https://oss.sonatype.org/content/repositories/releases"
                         :snapshots false
                         :releases {:checksum :fail :update :always}}
             "sonatype-snapshots" {:url "https://oss.sonatype.org/content/repositories/snapshots"
                                   :snapshots true
                                   :releases {:checksum :fail :update :always}}}
```
i have also tried converting the project.clj to deps.edn in my fork, but i still need to add these to my project that uses this library. maybe this is normal and needs to be added to the docs, or maybe there is a way to eliminate the dependant repos

**Comment by suvash** [comment]
I certainly haven't looked into the `deps.edn` requirements/structure yet for this project. Thanks for bringing this up. I'll take a look at it in the coming weeks and try to document it (and resolve anything if needed).

**Comment by suvash** [comment]
Sorry I'm going to close this as nobody else has reported any problems regarding this. Please reopen the issue (or better even submit a PR) if it's of concern.
