### ISSUE TITLE
(ot/get-totp-token secret-key) failing with Github 2fa, any ideas?

### ISSUE THREAD

**Issue by dtenny** [suvash/one-time#2]
Probably not a one-time issue, probably  just me and/or github.

I'm trying to use the one-time code to set up my github 2fa, but it rejects the token every time.

Is there perhaps some time-zone or other dependency I'm missing?  

I tried https://github.com/djui/clj-otp too, it's generating the same tokens, so unlikely a 'one-time' issue.

Sorry to ask here, didn't see other contact/forums for the question.

**Comment by dtenny** [comment]
Actually it may be something like hmac-sha-type or the nature of the key, I now have a secret key that causes this error: IllegalArgumentException Empty key  javax.crypto.spec.SecretKeySpec.<init> (SecretKeySpec.java:96)

**Comment by dtenny** [comment]
Found it.  Github prints the secret keys in lower case.  While one of those keys parsed fine, the other failed the hmac-digest routine (using both your lib and clj-otp).  That was my clue.  Doing a (.toUpperCase secret-key) before requesting the token fixed it.

**Comment by suvash** [comment]
Not sure how you were using this lib with Github 2FA (instead of using the Authenticator apps I'm assuming), but glad to know that it's working for you.
Could you still explain a bit more what you were working on, and where in the flow you were using this lib ?

**Comment by dtenny** [comment]
Turns out to be very simple.  When you go to the Github settings to activate 2fa in security, you can click a link for the shared secret (vs. QR codes/urls and other stuff for normal apps).

So I was cutting and pasting the shared secret into my calls to your library.  On the first shared secret key I was getting tokens, but Github was rejecting them all.  Later I tried again with a new shared secret key from Github, but that key was getting the exception I reported above ("empty key").  I got the same exception when I tried the Github supplied shared secret in another java based library too.

I guess one of the properties of base32 encoding is that it's a single case encoding (not mixed alphabetic case).  So I upcased the Github supplied shared secret and that fixed the problem.

So my advice is to document in README.md and/or docstrings that the secret key be upcased, or perhaps just put a call to upcase into the code.

Meanwhile, I signed into Github today with 2fa using your lib, yay!

**Comment by suvash** [comment]
Thanks for the explanation.
Seems like an issue that'll confuse more users. I'll do some research on this before adding documentation/implementing string cleanup. 🍻

**Comment by suvash** [comment]
Okay, I seem to understand the issue. (Base32 encoding only allows A-Z0-9, so valid secrets should be of that subset)
Something like below should suffice. If this is a big issue, I might consider adding this to util and update the docs to make it more clear.

``` clojure
(defn sanitize-string-to-base32-subset
  "Uppercase a string and cleanup everything that is not A-Z or 0-9"
  [string]
  (-> string
      (str/upper-case)
      (str/replace #"[^A-Z0-9]" "")))
```

**Comment by dtenny** [comment]
Not that my opinion counts for much, but if it were me I'd rather get an
exception on a string with outright non-compliant characters.

So I think the upper-casing of the input is okay, but the translation of
other invalid chars I would rather get an exception than have them silently
altered, it seems like a source of confusion down the road.

**Comment by suvash** [comment]
As a user, your feedback definitely counts.
Let me give this a thought and bake a good fix for the possible confusion into the next release, probably in a month or so.
